### ISSUE TITLE
Possible missing compiler parameter --std=c99

### ISSUE THREAD

**Issue by rojaster** [rednaga/APKiD#6] opened 2016-08-04 18:07 UTC
Hey , when i've tried to install apkid i got next error message:
```bash
yara/libyara/modules/dex.c: In function ‘load_proto_ids’:
yara/libyara/modules/dex.c:429:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0, p = 0; p < proto_ids_size; i += 1, p += sizeof(PROTO_ID_ITEM)) {
   ^
yara/libyara/modules/dex.c:429:3: note: use option -std=c99 or -std=gnu99 to compile your code
yara/libyara/modules/dex.c: In function ‘load_method_ids’:
yara/libyara/modules/dex.c:486:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0, p = 0; p < method_ids_size; i += 1, p += sizeof(METHOD_ID_ITEM)) {
   ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by rojaster** [comment] 2016-08-04 18:47
And I wasn't able to fix it by adding extra_compile_args = ['-std = c99 '] in 'setup.py':

```python
.......
    ext_modules=[Extension(
        name='yara',
        include_dirs=['yara/libyara/include', 'yara/libyara/', '.'],
        sources=['yara-python.c']
     # , extra_compile_args=["--std=c99"]
    )])

```

My solution is manual fix 'dex.c' in both lines :

```c
....
int i,p;
for (i = 0, p = 0; p < proto_ids_size; i += 1, p += sizeof(PROTO_ID_ITEM)) {
...
```

and after i installed with sudo and installation was without any errors.

Oh, and my OS is Ubuntu 14.04LTS(virtualbox)

**Comment by strazzere** [comment] 2016-08-04 21:00
Can you retry with a pull from the latest _yara-python_? It should be fixed as described in issue #3

**Comment by rojaster** [comment] 2016-08-08 12:18
```bash
git clone https://github.com/rednaga/yara-python
```
I am getting through your install recommendations. It takes last version from repository. 
And i read issue #3 , but, excuse me, it is not a solution i think, may be i am wrong.

proof from #3:
```bash
git clone https://github.com/rednaga/APKiD
cd APKiD
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
pip install apkid
```

> I have not installed `yara-python` from pip.

And one more: my default compiler is clang.

**Comment by strazzere** [comment] 2016-08-08 17:35
If you're only attempting to use `APKiD`, you only need to clone and install our specific _yara-python_ repo. Then you may perform a `pip` install apkid. Do not install _yara-python_ from `pip`. As this is not a version which contained our dalvik module.

So if you want to simply use this repo, follow the "Installing: instructions (clone _yara-python_, install, use `pip` to install `apkid`). Otherwise use the "Hacking" instructions.

Does this make sense? The code in our _yara-python_ should now be fully compatible with `clang`, even if they noisy flag are all set.

**Comment by rojaster** [comment] 2016-08-09 09:44
All steps to install APKiD i took from README.md - Installing
And i caught this error during build process of yara-python (from rednaga repository your specific yara-python, look above) after next commands:
```bash
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
```

OK, i will try again to go through installing process. But i think i will caught the same error.

**Comment by rojaster** [comment] 2016-08-09 10:16
On my laptop with `Ubuntu15.10+clang3.7.1` `yara-python` was builded successfully.
But on my virtual machine with `Ubuntu14.04.1+gcc` `yara-python` failed again on `dex.c` with the same error: --std=c99 flag is not set.
After manual editing `dex.c` as i note above build process is finished without this error.

**Comment by strazzere** [comment] 2016-08-09 17:11
I'm glad your issue is fixed, however I'm genuinely confused as the code in the custom repo already has that exact fix in it. ( https://github.com/rednaga/yara/commit/65410053ffb13d12eeea0a923f698b1141e2f67c )

Also, FWIW, you don't need to clone `APKiD` if you're going to use `pip` to install it.

**Closed by strazzere** 2016-08-09 17:11 UTC

**Comment by kolmai** [comment] 2016-10-11 20:16
I have a similar issue but with rules.c
I got the error bellow while I executing **python setup.py install** and following these steps:

```
git clone https://github.com/rednaga/APKiD
cd APKiD
git clone https://github.com/rednaga/yara-python
cd yara-python
python setup.py install
pip install apkid
```

error:
```
yara/libyara/rules.c: In function ‘yr_rules_save_stream’:
yara/libyara/rules.c:743:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
yara/libyara/rules.c:743:3: note: use option -std=c99 or -std=gnu99 to compile your code
error: command 'gcc' failed with exit status 1

```

**Comment by CalebFenton** [comment] 2016-10-11 20:38
What happens if you "use option -std=c99" as per https://github.com/rednaga/APKiD/issues/6#issuecomment-237646822 ?

**Comment by kolmai** [comment] 2016-10-11 20:44
Thanks for quick replay, haven't tried it yet. Could you share instructions please?

**Comment by CalebFenton** [comment] 2016-10-11 23:04
No problem. Instructions are linked to in my previous comment. Specifically, it's about adding a line to setup.py. Let me know if you have any specific questions about what's in the comment.

**Comment by kolmai** [comment] 2016-10-12 15:48
Thanks Caleb. I have added the extra args however the install didn't go through.
Here is what I got:

```
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/filemap.c -o build/temp.linux-x86_64-2.7/yara/libyara/filemap.o --std=c99
yara/libyara/filemap.c: In function ‘yr_filemap_map_fd’:
yara/libyara/filemap.c:228:5: warning: implicit declaration of function ‘madvise’ [-Wimplicit-function-declaration]
yara/libyara/filemap.c:228:53: error: ‘MADV_SEQUENTIAL’ undeclared (first use in this function)
yara/libyara/filemap.c:228:53: note: each undeclared identifier is reported only once for each function it appears in
error: command 'gcc' failed with exit status 1
```

**Comment by CalebFenton** [comment] 2016-10-12 16:23
Part of the reason I have no idea how to fix this is the problem is in a project full of code we didn't write that compiles a project full of code we didn't write using a build system I don't know. Also, I can't reproduce any of this. So I may ask a lot of dumb questions and you'll just have to bear with me :(

1. Have you tried `-std=c99`? Or did you use `--std=c99`?
2. What OS are you using?
3. What gcc version are you using?
4. What version of pip and python do you have installed?

**Comment by kolmai** [comment] 2016-10-12 16:33
No problem, let's do it.

1. Actually both
2. Ubuntu 12.04 64-bit
3. gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
4. pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7), Python 2.7.3

**Comment by CalebFenton** [comment] 2016-10-12 16:39
It might not help anything, but could you try upgrading pip? 

Does `pip install yara-python` work? This will install the official version, and I think there's some difference with how pip install compiles versus how setup.py install compiles.

If you clone the official yara project, does it compile without error?

**Comment by kolmai** [comment] 2016-10-12 17:16
I've tried upgrading pip and run `pip install yara-python`..
Successfully installed yara-python using pip. Cloning an official yara ended up with successful compilation as well.

**Comment by kolmai** [comment] 2016-10-21 19:47
Hello Caleb. Any updates on the error I've posted earlier?

```
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/usr/include/python2.7 -c yara/libyara/filemap.c -o build/temp.linux-x86_64-2.7/yara/libyara/filemap.o --std=c99
yara/libyara/filemap.c: In function ‘yr_filemap_map_fd’:
yara/libyara/filemap.c:228:5: warning: implicit declaration of function ‘madvise’ [-Wimplicit-function-declaration]
yara/libyara/filemap.c:228:53: error: ‘MADV_SEQUENTIAL’ undeclared (first use in this function)
yara/libyara/filemap.c:228:53: note: each undeclared identifier is reported only once for each function it appears in
error: command 'gcc' failed with exit status 1
```

**Comment by CalebFenton** [comment] 2016-10-21 20:03
Sorry, I haven't had time to look into this. I really have no special knowledge of what it could be, either. The Python package and build system is unusually baroque. I think we might be able to figure it out if we learn the difference between how yara is built using make, pip, and most importantly, setup.py. Once we understand the difference, there might be a way to have setup.py build stuff the same way.

One thing you could try is pip install the yara-python github repo.

**Comment by CalebFenton** [comment] 2019-01-09 21:11
I googled a similar problem recently and found this so I'll add a little extra detail.

I was trying to compile yara-python using gcc-4.x and it was failing and recommending `-std=c99` with the error originally posted. This didn't work, and I had to use `-std=gnu99`. Here's the final bit of the dockerfile I was using:
```
RUN set -ex ;\
    export CFLAGS='-std=gnu99' ;\
    pip wheel --wheel-dir=/tmp/yara-python \
        --build-option="build" \
        --build-option="--enable-dex" \
        git+https://github.com/rednaga/yara-python-1.git@master ;\
    pip install --no-index --find-links=/tmp/yara-python yara-python
```

Another work around is to use gcc-5:
```
RUN echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" > /etc/apt/sources.list.d/unstable.list &&\
    apt-get update &&\
    apt-get install --assume-yes -t unstable gcc-5 g++-5 &&\
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 &&\
    cc --version
```
