### ISSUE TITLE
Not matching resutls

### ISSUE THREAD

**Issue by drecker** [rednaga/APKiD#40] opened 2017-10-05 08:42 UTC
I have tried APKiO on several samples mentioned in sample output in https://rednaga.io/2016/07/30/apkid_and_android_compiler_fingerprinting/ but I actually get quite a few different results regarding compilers. for example for test-data/samples/unicom_sdk/bb11a710258077213ce4281e78a1c19a940c02dc3ddaa5f1d8046380173e0da7!classes.dex you have mentioned Android SDK (dexmerge), dexlib 1.x in article but running it on my machine I get dx (possible dexmerge). For test-data/samples/apkprotect/9ac20091b8e82c8ff2882422450e30c03043136ca009affe59e51edabf753337 there is dexlib 1.x but I got dexlib 2.x

**Comment by CalebFenton** [comment] 2017-10-05 17:02
I believe in both cases the rules were wrong at the time the blog content was created. I get the same output as you on my machine, and I manually confirmed the rules were right.

bb11a710258077213ce4281e78a1c19a940c02dc3ddaa5f1d8046380173e0da7 - string offsets are increasing (not dexlib1), map type order consistent with dexmerge. technically, dex could have been compiled with dexlib2.x and then merged, it's much more common for dexmerge to imply dx compiler since official tools configured this way by default. hence "dx (possible dexmerge)".

9ac20091b8e82c8ff2882422450e30c03043136ca009affe59e51edabf753337 - string offsets are increasing, so not dexlib1. map type order consistent with dexlib2.

Rules have been tightened up since the original release, so I'm not surprised. Good catch.

**Closed** 2017-10-15 22:48 UTC
