### ISSUE TITLE
Apkid crashes when CRC-32 is not valid for classes.dex

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#62] opened 2017-11-28 19:04 UTC
The example merged-牄ҡ約.bin is either an ODEX file or a memory dump from GDB. However, the error could be try-catch-ed.

```
2017-11-27 18:35:54 ERROR    error extracting ./gdb-dumps/merged-牄ҡ約.bin: Bad CRC-32 for file 'classes.dex'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/apkid.py", line 135, in scan_apk
    zf.extractall(td, members=target_members)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/zipfile.py", line 632, in read
    data = self.read1(n - len(buf))
  File "/usr/lib/python2.7/zipfile.py", line 692, in read1
    self._update_crc(data, eof=eof)
  File "/usr/lib/python2.7/zipfile.py", line 647, in _update_crc
    raise BadZipfile("Bad CRC-32 for file %r" % self.name)
BadZipfile: Bad CRC-32 for file 'classes.dex' 
```

**Comment by strazzere** [comment] 2019-10-01 17:15
This appears to be that the crc32 for the dex file /as listed in the zip entry/ is invalid, so it's actually a zip bug again, dupe of #54

**Closed by strazzere** 2019-10-01 17:15 UTC
Labels: duplicate
