### ISSUE TITLE
Apkid crashes with IOError while scan_apk

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#63] opened 2017-11-28 19:06 UTC
Example:

```
2017-11-27 18:35:54 ERROR    error extracting ./gdb-dumps/merged-樗蒈Ի.bin: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/apkid.py", line 135, in scan_apk
    zf.extractall(td, members=target_members)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1082, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib/python2.7/zipfile.py", line 963, in open
    zef_file.seek(zinfo.header_offset, 0)
IOError: [Errno 22] Invalid argument 
```

**Comment by strazzere** [comment] 2019-10-01 17:13
I believe this is essentially a dupe of #54

**Closed by strazzere** 2019-10-01 17:13 UTC
Labels: duplicate
