### ISSUE TITLE
Apkid should not crash when permission is denied

### ISSUE THREAD

**Issue by enovella** [rednaga/APKiD#60] opened 2017-11-27 20:01 UTC
Example:
```
$ apkid .
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
Traceback (most recent call last):
  File "/usr/local/bin/apkid", line 11, in <module>
    load_entry_point('apkid==1.0.0', 'console_scripts', 'apkid')()
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/__init__.py", line 60, in main
    apkid.scan(input, args.timeout, args.json)
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/apkid.py", line 176, in scan
    for file_type, file_path in collect_files(input):
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/apkid.py", line 76, in collect_files
    file_type = get_file_type(filepath)
  File "/usr/local/lib/python2.7/dist-packages/apkid-1.0.0-py2.7.egg/apkid/apkid.py", line 54, in get_file_type
    with open(file_path, 'rb') as f:
IOError: [Errno 13] Permission denied: './pureVPN/openvpncfg/login.conf'
```

**Comment by strazzere** [comment] 2019-10-01 17:16
Dupe of #56

**Closed by strazzere** 2019-10-01 17:16 UTC
Labels: duplicate
