### ISSUE TITLE
[DETECTION] Android 10 built apk's use an unknown compiler

### ISSUE THREAD

**Issue by strazzere** [rednaga/APKiD#190] opened 2019-12-25 23:32 UTC
**Provide the file**
[unknown-compiler.zip](https://github.com/rednaga/APKiD/files/4000891/unknown-compiler.zip)
`03aa9fb6b1ac91ef36f9951c8b5846ef40caa12756a47283f59e06c484d7692e  classes.dex`

*If you do no fill in this section, the issue with be closed due to lack of the bare minimum of information needed for people to reproduce. We CANNOT test things if you don't tell use what to test*

**Describe the detection issue**
Android 10 built dex, doesn't detect as a known compiler, need to dive into the build system and see what they replaced/changed for Android 10 branches.

**APKiD current results...**
Please provide current output from APKiD on this file. Include the APKiD header which provides the version, e.g. -
```
diff@larry: apkid classes.dex 
[+] APKiD 2.1.0 :: from RedNaga :: rednaga.io
[*] classes.dex
 |-> compiler : unknown (please file detection issue!)
```

**Additional context**

**Comment by CalebFenton** [comment] 2019-12-30 19:13
Thanks for finding this.


And for actually filling out the issue template... ![](https://www.reactiongifs.com/r/jack.gif)

**Comment by strazzere** [comment] 2019-12-31 00:03
There is an upstream bug that we'll need to resolve to get this fully working :\

The dex module that is currently merged into yara 3.11 bombs out if there is a new dex magic;
https://github.com/VirusTotal/yara/blob/ed1a1a430c64cf908b61a5fadc3958866a840bc6/libyara/modules/dex.c#L306-L309

**Comment by CalebFenton** [comment] 2020-01-01 20:03
I was able to reproduce this issue by using a new template probject from android stuido.

The file looks compiled by dx and I think the issue is related to https://github.com/rednaga/APKiD/issues/198

Indeed, the dex is "dex 039" so I changed it to 038 and apkid worked fine. Going to create a PR to fix this.

This is the reason apkid doesn't care about the specific version.

**Comment by CalebFenton** [comment] 2020-01-01 20:08
https://github.com/VirusTotal/yara/pull/1190 now just need to get that reviewed and merged and wait for yara-python to pick it up also. So yeah, probably time to switch back to our own fork since this might take a few months :(

**Comment by strazzere** [comment] 2020-01-01 20:59
Makes sense that it's related to #198 -- though, digging into the file a bit, I think Android Studio does not use `dx` anymore, though it does use `r8` (aka `d8`) -- though the rule we have for DX (looking at what is in slot `7` of the `map`) is essentially the same.

**Comment by CalebFenton** [comment] 2020-01-01 21:25
I'll see if there are any differences between the two.

**Comment by strazzere** [comment] 2020-01-01 21:29
For reference, I was looking at https://r8.googlesource.com/r8/+/refs/heads/master/src/main/java/com/android/tools/r8/dex/FileWriter.java#727 -- since it was sort of a pain to track down the `d8` compiler since it's labelled internally as `r8`

**Comment by CalebFenton** [comment] 2020-01-03 01:34
Added r8 detection with https://github.com/rednaga/APKiD/commit/b76b8ce577c0eeedb348b3aae0e9a053cbad53e4

**Closed by CalebFenton** 2020-01-03 01:34 UTC
Labels: detection-issue
